---
title: "SQL Series: Database Normalization, ER Diagrams, and Queries"
author: "Data Girls"
date: "03-13-2021"
output:  statsr:::statswithr_lab
---
   
```{r include=FALSE}
library(shiny)
```
## Table of Contents

- [Introduction](#Introduction)
  - [Data Generation and ER diagram]
  - [Normalization]
- [Table Description]
- [Queries]

### Introduction

The database I decided to work with contains data from a Watercraft Management Company which manages 7 other companies that offer watercrafts for rent. 
The database keeps track of clients and the companies they have rented watercrafts from. 

Since the management company serves as a client generator for the companies it works with, it takes 10% of the amount that each customer pays. 
The company collects revenues at the end of the booking and it has records from 1/1/2016 till 1/4/2019.
It contains data from a Watercraft Management Company which manages 7 other companies that offer watercrafts for rent. 
The database keeps track of clients and the companies they have rented watercrafts from. 
The company collects revenues at the end of the booking and it has records from 1/1/2016 till 1/4/2019.
Several additions have been made to the database. Changes include: primary key fields which make the normalization of the database less painful. 

#### Data Generation and ER diagram

In order to supply the dataset with data, I used `DataFactory` which is a Java library that allows you to generate random data.
The Java code I wrote for random data generation can be found in this project's folder. 

Path: `cs205_midterm_project/my_app/src/main/java/com/mycompany/app`.

I had to use Apache Maven to provide the Java file that generates the data with the necessary dependencies for DataFactory, so that is why the
project contains so many directories. 

[Click here](https://github.com/andygibson/datafactory) to be directed to the source code of DataFactory . 

For ER diagrams, I used [dbdiagram.io](https://dbdiagram.io/home). 

#### Normalization

The data I generated was initially contained in one table, but through normalization, 7 other tables were created. 
The script that normalizes the data base can be found under the name `normalized_watercrafts.sql`, while the counts can be found under `normalization.sql`. 

### Table Description

`nor_customer`

| Field  | Description  |
|------------|-------------------------------------------|
|`customer_id`| `Primary key` field that identifies customers. |
|`customer_name`  | Name of the customer.|
|`customer_card`|Type of customer card. In this watercraft management data set there are 4 types of customer cards, respectively `A`, `B`, `C`, `D`. `Foreign key` field that refers to cus_discount table.|
|`damage_type`  | This field records possible damages that might have been inflicted upon the watercraft. `Foreign key` that refers to the damages table|

`nor_watercrafts`

| Field  | Description  |
|------------|-------------------------------------------|
|`watercraft_id`| `Primary key` field that identifies watercrafts.|
|`watercraft_type`| Type of watercraft.|
|`price`| Price of each watercraft per day.|

`nor_company`

| Field  | Description  |
|------------|-------------------------------------------|
|`company_id`|`Primary key` field that identifies companies.|
|`company_name`|Name of each company.|
|`city`| The city, each company is located in.|
|`cso_id`|Id of the Chief Sales Officer of each company. `Foreign key` field that refers to the cso_table table|

`nor_booking`

| Field  | Description  |
|------------|-------------------------------------------|
|`booking_id`|`Primary key` field that identifies each booking.|
|`customer_id`|`Foreign key` field that identifies customers.|
|`watercraft_id`|`Foreign key` field that identifies watercrafts.|
|`comapny_id`|`Foreign key` field that identifies companies.|
|`booked_from`|Staring day of the rent.|
|`booked_till`|Ending day of the rent.|
|`flag`|Custom flags for watercrafts. This is more of an accessory. Flags: `Greek` `Turkish` `Albanian` `American` `Dutch` `Japanese` `British`. Since flags are assigned upon registration they are included in the booking table.|

`cus_discount`

| Field  | Description  |
|------------|-------------------------------------------|
|`customer_card`|`Primary key` field. Type of customer card. In this watercraft management data set there are 4 types of customer cards, respectively `A`, `B`, `C`, `D`. |
|`discount`| Discount on percentage. Type `A` card gets 20% discount, Type `B` card gets 15% discount. Type `C` card gets 10% discount and type `D` gets no discount.|

`damages`

| Field  | Description  |
|------------|-------------------------------------------|
|`damage_type`|`Primary key` field that indicated the type of damage.|
|`damage_fee`|Fee that the customer is obliged to pay if they have damaged the watercraft.|

`cso_table` 

| Field  | Description  |
|------------|-------------------------------------------|
|`cso_id`|`Primary key` field that identifies Chief Sales Officers. There is one CSO per each company.|
|`cso_name`| Name of the CSO.|
|`shares`| Shares each CSO holds.|

### Queries

#### Q1: Display how much money was spent on each type of watercraft. 
`EXPLANATION: `
First,  we calculate total revenues, then join the tables that contain the fields we are interested in and then group by watercraft type. 

`CODE:`
```
select
  w.watercraft_type, 
  sum(((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee) "Money spent on each watercraft"
  from nor_booking b 
         join nor_watercraft w on (b.watercraft_id = w.watercraft_id)
         join nor_customer c on (b.customer_id = c.customer_id)
         join damages d on (c.damage_type = d.damage_type)
         join cus_discount cd on (c.customer_card = cd.customer_card)
         join nor_company co on (b.company_id = co.company_id)
         join cso_table ct on (co.cso_id = ct.cso_id)
 group by w.watercraft_type;
 
```
#### Q2: Display the most profitable company in the year with the least revenues. 

`EXPLANATION: `

First, a view that shows profits grouped by year and sorted by the amount of revenues in ascending order to get the year with the lowest amount of revenues is created. 
Then, the company with the most profits in this year is displayed. 

`CODE:`

```
create or replace view no_watercrafts_v1 as
select to_char(b.booked_till, 'YYYY') year,
       to_char(sum((((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee) - (0.05 * (((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee))), '$9,999,999.00')
"Total Revenues"
  from nor_booking b 
         join nor_watercraft w on (b.watercraft_id = w.watercraft_id)
         join nor_customer c on (b.customer_id = c.customer_id)
         join damages d on (c.damage_type = d.damage_type)
         join cus_discount cd on (c.customer_card = cd.customer_card)
         join nor_company co on (b.company_id = co.company_id)
         join cso_table ct on (co.cso_id = ct.cso_id)

 group by to_char(b.booked_till, 'YYYY')
 order by 2 asc;


```

```
select * from(
select co.company_id,  
       to_char(sum((((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee) - (0.05 * (((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee))), '$999,999.00') "Profits"
  from nor_booking b
         join nor_watercraft w on (b.watercraft_id = w.watercraft_id)
         join nor_customer c on (b.customer_id = c.customer_id)
         join damages d on (c.damage_type = d.damage_type)
         join cus_discount cd on (c.customer_card = cd.customer_card)
         join nor_company co on (b.company_id = co.company_id)
         join cso_table ct on (co.cso_id = ct.cso_id)
 where to_char(b.booked_till, 'YYYY') = (select year from no_watercrafts_v1 WHERE rownum = 1)
 group by co.company_id
 order by 2 desc
)
               where rownum = 1;

```
#### Q3: Show how much profits has each CSO made throughout the years. Show years in separate columns. 
`EXPLANATION:`
The code is self-explanatory. `ct.shares` indicates the shares the CSO holds. 

`CODE:`

```
select ct.cso_name,
       sum(decode(to_char(b.booked_till, 'YYYY'),'0016',(ct.shares*(((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee) - (0.05 * (((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee))), 0)) "2016" ,
       sum(decode(to_char(b.booked_till, 'YYYY'),'0017',(ct.shares*(((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee) - (0.05 * (((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee))),0)) "2017",
       sum(decode(to_char(b.booked_till, 'YYYY'),'0018',(ct.shares*(((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee) - (0.05 * (((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee))),0)) "2018",
       sum(decode(to_char(b.booked_till, 'YYYY'),'0019',(ct.shares*(((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee) - (0.05 * (((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee))),0)) "2019"
  from nor_booking b
         join nor_watercraft w on (b.watercraft_id = w.watercraft_id)
         join nor_customer c on (b.customer_id = c.customer_id)
         join damages d on (c.damage_type = d.damage_type)
         join cus_discount cd on (c.customer_card = cd.customer_card)
         join nor_company co on (b.company_id = co.company_id)
         join cso_table ct on (co.cso_id = ct.cso_id)

 group by ct.cso_name;


```


#### Q4: Show how many watercrafts of each type has every company rented out. Order by company name in this order: 

- Santa-Lucia-Dock-Company
- Silk-Waters
- Illyria-Docks
- Rogers-Dock
- Ruwais-Marine-Services
- Tides-Marina
- Bouzakis-Bros-Marine

`CODE:`

```
select c.company_name,
       count(decode(lower(w.watercraft_type), 'fishing boat', w.watercraft_id, 0)) "Fishing Boat",
       count(decode(lower(w.watercraft_type), 'catamaran boat', w.watercraft_id, 0)) "Catamaran boat",
       count(decode(lower(w.watercraft_type), 'yacht', w.watercraft_id, 0)) "Yacht",
       count(decode(lower(w.watercraft_type), 'cabin-cruiser-boat', w.watercraft_id, 0)) "Cabin-Cruiser-Boat",
       count(decode(lower(w.watercraft_type), 'house-boat', w.watercraft_id, 0)) "House Boat",
       count(decode(lower(w.watercraft_type), 'jet-ski', w.watercraft_id, 0)) "Jet-ski",
       count(decode(lower(w.watercraft_type), 'boat', w.watercraft_id, 0)) "Boat"
  from nor_booking b
         join nor_company c on (b.company_id = c.company_id)
         join nor_watercraft w on (w.watercraft_id = b.watercraft_id)
  group by c.company_name
  order by decode(c.company_name,
                  'Santa-Lucia-Dock-Company', 9,
                  'Silk-Waters', 8,
                  'Illyria-Docks', 7,
                  'Rogers-Dock', 6,
                  'Ruwais-Marine-Services', 5,
                  'Tides-Marina', 4,
                  'Bouzakis-Bros-Marine', 3) desc;


```




#### Q5: Show the name of the CSO, the amount they have made during the entire period and how many customers have been served by their company. Order by revenues in ascending order and then by number of customers in descending order. 
Show only those CSO that served more than 15 customers and made more than $200000 during the entire period. 

`CODE: `

```
select ct.cso_name, 
       sum((ct.shares*(((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee) - (0.05 * (((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee)))) Revenues, count(c.customer_id) "Number of Customers"
         from nor_booking b
         join nor_watercraft w on (b.watercraft_id = w.watercraft_id)
         join nor_customer c on (b.customer_id = c.customer_id)
         join damages d on (c.damage_type = d.damage_type)
         join cus_discount cd on (c.customer_card = cd.customer_card)
         join nor_company co on (b.company_id = co.company_id)
                join cso_table ct on (co.cso_id = ct.cso_id)
 group by ct.cso_name
having count(c.customer_id) > 15
       and sum((ct.shares*(((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee) - (0.05 * (((w.price *  (b.booked_till - b.booked_from))-(w.price*cd.discount)) +d.damage_fee)))) > 200000
 order by 2 asc, 3 desc

```

#### Q6: For every company show the name, location, number of customers during 2019 and how much it has made on damages only.

`CODE:`

```

select co.company_name, co.city, count(cu.customer_id) "Customers", sum(d.damage_fee) "Revenues on damages"
  from nor_booking b
         join nor_company co on (b.company_id = co.company_id)
         join nor_customer cu on (b.customer_id = cu.customer_id)
         join damages d on (cu.damage_type = d.damage_type)
         where to_char(b.booked_till, 'YY') = '19'
 group by co.company_name, co.city
 order by 3 desc, 4 desc;


```

#### Q7: Show how many times every particular type of damage has been caused by each type of customer. 

`CODE`
 
 ```
 
select d.damage_type, count(decode(cu.customer_card, 'A', d.damage_fee, 0)) "TYPE A",
       count(decode(cu.customer_card, 'B', d.damage_fee, 0)) "TYPE B",
             count(decode(cu.customer_card, 'C', d.damage_fee, 0)) "Type C",
                   count(decode(cu.customer_card, 'D', d.damage_fee, 0)) "TYPE D"
                         from nor_customer cu
                         join damages d on(cu.damage_type = d.damage_type)
                         group by d.damage_type
                         order by 2 desc;
 ```

`This report was created using RMarkdown and then a pdf converter. The RMarkdown document and the html one can be found in rmarkdown_file folder. ASK ANY QUESTIONS YOU MIGHT HAVE IN THE DISCORD CHAT :)`



  






